# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
    - pio run -e huzzah
    deps:
      - compiledb
    silent: true

  compiledb:
    cmds:
    - pio run -t compiledb -e huzzah

  upload:
    cmds:
    - pio run -e huzzah -t upload
    silent: true

  test:
    cmds:
    - pio test -e native -v
    silent: true

  monitor:
    cmds:
    - pio device monitor
    silent: true
